spring.application.name=servicehubBackend

spring.datasource.url=jdbc:mysql://localhost:3306/servicehub_db
spring.datasource.username=root
spring.datasource.password=sru_thi321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080